### ISSUE TITLE
Format .php file with mixed php code and html

### ISSUE THREAD

**Issue by scottfriebel** [dericofilho/sublime-phpfmt#123]
This bug: https://github.com/dericofilho/sublime-phpfmt/issues/78 also describes the issue I'm having.

The php code is formatted but the indentation is lost so regardless of the indentation of the html, the first line inside the opening <?php tag is moved to the first column and the rest of the php is indented according to that.
I have the most up to date version (sublime should keep it updated anyway), and I've uninstalled and reinstalled it to make sure.

````php
<div class="bodyDiv clearFix">
	<div class="leftNavDiv">
 		<ul class="subHeadingList">
			<?php
if ($vCurrentSubSection == 'General') {
	echo '<li class="active">General</li>';
}
?>
		</ul>
	</div>
</div>
````

**Comment by dericofilho** [comment]
@scottfriebel I am really sorry for this inconvenience. However there is little I can do about it, because the formatter relies on php's token_get_all. It means it tokenizes only PHP tokens and not HTML tokens outside of PHP tag. Moreover, it is impossible to know for sure what's outside of PHP tags, it could be XML, HTML, JSON, binary etc. Each one with its own syntax rules and indentation rules. 

I do not rule, in the future, to embed a HTML formatter inside the PHP formatter, se cases like this are properly dealt with. But right now, I cannot fix this issue for you. I am sorry.

**Comment by scottfriebel** [comment]
I understand. Thanks for the quick reply!

**Comment by crimsonvspurple** [comment]
Just wanna say that it'd be really cool to have this.

**Comment by dericofilho** [comment]
@crimsonvspurple There is a beta support for this. It will format PHP code and will try to place PHP code properly when mixing with HTML. Consider adding `AlignPHPCode` in `passes` inside of your configuration file.

**Comment by crimsonvspurple** [comment]
Thanks. Will try it out.

Does it only align php code with html or formats html code too?

I wish there was a solution that could properly format a file with PHP, HTML, JS, CSS...all at once.

**Comment by dericofilho** [comment]
Only PHP. I do not discard supporting other languages in future.
