### ISSUE TITLE
i use win8 for sublime

### ISSUE THREAD

**Issue by ppker** [dericofilho/sublime-phpfmt#144]
my config 
+++++++
{
"version": 2,
 //"php_bin":"/wamp/bin/php/php5.5.12/"
 //"format_on_save":true
}
++++++++++
{
 "enable_auto_align": true,
 "format_on_save": true,
 "php55warning": true,
 "psr1": true,
 "disable_auto_align":false
}
+++++++++++++++
this is can be go
this is cool

**Comment by dericofilho** [comment]
@ppker Could you please be elaborate more?

**Comment by ppker** [comment]
i don't need to write "php_bin",
i want to know the "php_bin".  because i write this,that is Error.
can't find php  binary file
so i remove the "php_bin" setting

**Comment by dericofilho** [comment]
@ppker If I understood you correctly, you are not properly formatting the json file. I believe you are omitting commas when you shouldn't - or putting commas where they are not expected.

Instead of this:
```
{
"version": 2,
"php_bin":"/wamp/bin/php/php5.5.12/"
"format_on_save":true
}
```

Try this:
```
{
"version": 2,
"php_bin":"/wamp/bin/php/php5.5.12/",
"format_on_save":true
}
```

Or, if you really want to get rid of `php_bin`, consider properly format the json such:
```
{
"version": 2
}
```

**Comment by dericofilho** [comment]
@ppker If I do not hear back until June 19th, I shall close this issue.
