### ISSUE TITLE
Allow for the ability to disable the formatter for specific blocks of code

### ISSUE THREAD

**Issue by cjmaio** [dericofilho/sublime-phpfmt#92]
Great plugin, by the way!

One issue I've run into using it is the case when you need to disable the formatter for specific blocks of code. I get this a lot when doing development for WordPress... where functions need to be formatted like... `plugin_basename` rather than `pluginBasename` however I'd like to continue to use the formatter on the rest of the code I use Sublime for.

Would adding in something like Eclipse has for its formatter...
    
    // @formatter:off
    // CODE HERE
    // @formatter:on

Be of use to anyone?

**Comment by dericofilho** [comment]
@cjmaio thanks for your suggestion. It seems an one particular case that of yours. I should like to see more interested from the rest of the community before actually implementing it. 

The real problem is in the fact that such skipping of code will create a very big exception case in the code, which I need to think very carefully about it. 

Also, I plan to restore the option "format selection". Would it serve you too, perhaps?

**Comment by cjmaio** [comment]
That could definitely work, yeah. I only threw this out there to see if
there'd be more use cases.

Another option would be a way to disable automatic formatting on save on a
per file basis. That way I could format code in a particularly nasty file
by selecting it, but not giving up my auto formatting on save for most of
my projects.

**Comment by dericofilho** [comment]
@cjmaio OK. Let's see if any of this spark more feedback from user base.

**Comment by dericofilho** [comment]
There was not response from user base. Thus I am closing this issue. I shall in some point in the future, restore the option to format selection only. I shall keep you posted through this issue.
