### ISSUE TITLE
Is it possible to add indent size option? (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [dericofilho/sublime-phpfmt#96]
Hi,
It's necessary to add `indent_size` option to `phpfmt.sublime-settings`.
For now the indent size is 4.

Regards.

**Comment by dericofilho** [comment]
@joseluisq I am sorry for this inconvenience. Have you considered adding this to your configuration file?

```
...
"indent_with_space": 8, // replace 8 with the number of spaces you want.
...
```

**Comment by joseluisq** [comment]
I try it, this works , but in your default `phpfmt.sublime-settings` settings I see:  `"indent_with_space": false`

I think an `indent_size` option could be better explicit
What do yout think?

**Comment by dericofilho** [comment]
`indent_size` in the beginning was considered an option, but it created an issue because part of ST thought it was actually changing  ST configuration. Moreover, indent size does not affect the length of tab sizes, which could lead to more ambiguity. 

In the end,  the confusion was settled down with the `indent_with_spaces`,that it makes explicit two important things: one, this is about converting tabs to space. Second, it is not an editor configuration option. Thus I would discard the idea of renaming the parameter on these merits. 

To make matters worse, this change will create a backward compatibility issue. I would need to bump a major version and create a configuration file migration algorithm - tools one tasks, when other more urgent matters have not been fixed yet.

**Comment by joseluisq** [comment]
Wow, I understand now, in this case the `  README.md` file should have to explain the possible values `indent_with_space` in **Settings** section.

**Comment by dericofilho** [comment]
I will update it accordingly.

**Comment by joseluisq** [comment]
Perfect thanks for your support :+1:
