### ISSUE TITLE
Add .editorconfig support (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [dericofilho/sublime-phpfmt#97]
Hi,
I think it will be great option to add support to `.editorconfig` settings for cross-editors in near future.
More info about [editorconfig](http://editorconfig.org/).

Regards

**Comment by dericofilho** [comment]
@joseluisq I appreciate this suggestion. Right now, I am focusing in streamlining the plugin internals, which is currently messy. I shall add support for editorconfig some point in the medium-term future, as I use it myself too.

**Comment by dericofilho** [comment]
I leave this issue option to fetch +1 from the user base.

**Comment by joseluisq** [comment]
Sure, I understand you timeline. 
Great :+1:

**Comment by dericofilho** [comment]
There is low interest from user base it seems. It will still be done some day, though.

**Comment by simnom** [comment]
Actually I'd take configuration in .editorconfig over pre project settings to be honest.

**Comment by dericofilho** [comment]
@simnom @joseluisq I have added the support for automatic search of ".php.tools.ini" file. Editorconfig is meant to configure the editor, whereas .php.tools.ini is meant to configure just the plugin. More importantly, there are several advanced configurations that cannot fit in .editorconfig file; that's why I am adding the support for .php.tools.ini file.

Upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/2.11.0 and give it a try. 
Add a .php.tools.ini in the root of your project, and within the file the same parameters from command line call to fmt.phar. For instance:

```
psr2=1
passes=ReturnNull
```

**Comment by joseluisq** [comment]
It's a good idea :+1:
